title: "مقالات تقنية"
author: "Pantera"
description: "مدونة تقنية عربية تغطي مواضيع البرمجة والتقنية"
url: "https://roko-tech.github.io"
permalink: /:title/
lang: "ar"
excerpt_separator: "\n\n\n"
date_format: "%d-%m-%Y"
paginate: 8
# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false            # use a dark header
show_related: true
back_to_top: true
back_to_top_text: "العودة للأعلى"

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "الرئيسية"}
  - {file: "archive.html", title: "الأرشيف"}
  - {file: "about.html", title: "عن المدونة"}
  - {url: "https://x.com/rokogan", title: "X"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {file: "index.html", title: "الرئيسية"}
  - {url: "/feed.xml", title: "RSS"}

comments:
  giscus: true
  giscus_repo: "roko-tech/roko-tech.github.io"

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap
