title: "مقالات تقنية"
author: "Pantera"
description: "مدونة تقنية عربية تغطي مواضيع البرمجة والتقنية"
url: "https://roko-tech.github.io"
timezone: "Asia/Riyadh"
defaults:
  - scope:
      path: ""
    values:
      image: /assets/og-default.png
permalink: /:title/
lang: "ar"
excerpt_separator: "\n\n\n"
date_format: "%d-%m-%Y"
paginate: 8
# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # uses frame.sass stylesheet
show_related: true
back_to_top: true
back_to_top_text: "العودة للأعلى"

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "الرئيسية"}
  - {file: "archive.html", title: "الأرشيف"}
  - {file: "editor.html", title: "المحرر"}
  - {url: "https://x.com/rokogan", title: "X"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {file: "index.html", title: "الرئيسية"}
  - {url: "/feed.xml", title: "RSS"}

comments:
  giscus: true
  giscus_repo: "roko-tech/roko-tech.github.io"
  giscus_repo_id: "R_kgDOHOjIZg"
  giscus_category: "General"
  giscus_category_id: "DIC_kwDOHOjIZs4C5G48"

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-redirect-from
