title: ""
author: "Pantera"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "ar"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
paginate: 1
paginate_path: "/blog/page:num/"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Pantera"}
  - {file: "archive.html"}
  - {url: "https://twitter.com/rokogan", title: "Twitter"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Twitter, icon: twitter, url: "https://twitter.com/rokogan"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
  disqus: True
  disqus_shortname: "https-rokogan-github-io"    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-paginate
